name: Daily Auto Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00（北京时间8:00）
  workflow_dispatch:      # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 赋予写入权限
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # 获取所有历史记录

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/yoursmile66/TVBox.git
        git fetch upstream

    - name: Merge changes from upstream
      run: |
        # 设置Git用户信息
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 尝试合并，如果冲突则退出
        if ! git merge upstream/main --no-edit; then
          echo "Merge conflict detected! Please resolve manually."
          exit 1
        fi

    - name: Push changes to origin
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}